### ISSUE TITLE
RuntimeError: Session is closed

### ISSUE THREAD

**Issue by yichengchen** [m13253/openwepro#1]
When I put this software running in background,After a few time,come with this error.

> 500 Internal Server Error
> 
> Server got itself in trouble
> Traceback:
> 
> Traceback (most recent call last):
>   File "/opt/python-3.4.3/lib/python3.4/site-packages/aiohttp/server.py", line 266, in start
>     yield from self.handle_request(message, payload)
>   File "/home/openwepro/src/weproserver.py", line 48, in handle_request
>     return (yield from self.do_http_proxy(message, payload, target_url))
>   File "/home/openwepro/src/weproserver.py", line 97, in do_http_proxy
>     request = yield from aiohttp.client.request(message.method, url, data=(yield from payload.read()), headers=request_headers, allow_redirects=False, version=message.version, connector=self.upstream_connector)
>   File "/opt/python-3.4.3/lib/python3.4/site-packages/aiohttp/client.py", line 578, in **iter**
>     return (yield from self._coro)
>   File "/opt/python-3.4.3/lib/python3.4/site-packages/aiohttp/client.py", line 150, in _request
>     raise RuntimeError('Session is closed')
> RuntimeError: Session is closed

**Comment by m13253** [comment]
Can you reproduce this issue? And can you tell me which distribution and its version you are using?

Thanks.

**Comment by yichengchen** [comment]
I am running it on a debian7.7 server with Python 3.4.3
I found the simplest way to reproduce the issus is try to access a error url such as http://wikipedias.org this would Obviously raise a error "[Name or service not known]" But After that,even I visit the correct website wikipedia.org it raise the RuntimeError: Session is closed.

I doubt that once someone visit or website contain a url which is unreachable.The session of whole service will go down.

**Comment by m13253** [comment]
Thank you. I reproduced the same error.

I think the problem lies on the package `aiohttp.client`. I am busy these days, and I will look into this problem soon.

**Comment by m13253** [comment]
Bug reported to upstream: https://github.com/KeepSafe/aiohttp/issues/883
